worker_processes auto;
rtmp_auto_push on;
events {}

rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;

        application live {
            live on;
            record off;
            # This is where your phone will stream: rtmp://<server-ip>/live/irl
            # OBS will pull from here
        }
    }
}
